
default: &default
  adapter: postgresql
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: toptal_development

test:
  <<: *default
  database: toptal_test

production:
  <<: *default
  database: toptal_production
