
default: &default
  adapter: postgresql
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: toptal_development

test:
  <<: *default
  database: toptal_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || Integer(ENV['CABLE_POOL_SIZE'] || 10) + Integer(ENV['MAX_THREADS'] || 5) %>
